services:

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: password

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  #  node-exporter:
  #    image: quay.io/prometheus/node-exporter:latest
  #    ports:
  #      - '9100:9100'
  #    networks:
  #      - monitoring

  #  postgres:
  #    image: postgres:latest
  #    environment:
  #      POSTGRES_USER: myuser
  #      POSTGRES_PASSWORD: mypassword
  #      POSTGRES_DB: common_db
  #    ports:
  #      - '5433:5432'
  #    networks:
  #      - monitoring
  #    volumes:
  #      - pg-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - monitoring

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
                       -Dcom.sun.management.jmxremote.authenticate=false \
                       -Dcom.sun.management.jmxremote.ssl=false \
                       -Dcom.sun.management.jmxremote.rmi.port=9999 \
                       -Djava.rmi.server.hostname=kafka"
      KAFKA_OPTS: "-javaagent:/etc/jmx-exporter/jmx_prometheus_javaagent-1.0.1.jar=1234:/etc/jmx-exporter/jmx_exporter_config.yml"
    ports:
      - "29092:29092"
      - "9999:9999"
      - "1234:1234"
    depends_on:
      - zookeeper
      - prometheus
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka/jmx_exporter_config.yml:/etc/jmx-exporter/jmx_exporter_config.yml
      - ./kafka/jmx_prometheus_javaagent-1.0.1.jar:/etc/jmx-exporter/jmx_prometheus_javaagent-1.0.1.jar
    networks:
      - monitoring

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "9000:8080"
    depends_on:
      - kafka
    networks:
      - monitoring

  kafka-exporter:
    image: bitnami/kafka-exporter:latest
    command: [ "--kafka.server=kafka:9092" ]
    ports:
      - "9308:9308"
    depends_on:
      - kafka
    networks:
      - monitoring

volumes:
  kafka-data: { }
  pg-data: { }

networks:
  monitoring:
    driver: bridge