global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka:1234' ]
#  - job_name: 'kafka UI'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ 'kafka-ui:8080' ]
#        labels:
#          application: 'Kafka UI'
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Application'
  - job_name: 'kafka-exporter'
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
        labels:
          application: 'Kafka exporter'
#  - job_name: 'node-exporter'
#    metrics_path: '/metrics'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ 'node-exporter:9100' ]
#        labels:
#          application: 'Node exporter'