global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Application'
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          application: 'Node exporter'